/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const game_loop: () => [number, number];
export const get_achievements_html: () => [number, number];
export const get_cube_details_html: (a: number) => [number, number];
export const get_cubes_grid_html: () => [number, number];
export const get_selected_cube_id: () => number;
export const go_to_menu: () => [number, number];
export const handle_key_down: (a: number, b: number) => [number, number];
export const handle_key_up: (a: number, b: number) => [number, number];
export const hide_menu: () => [number, number];
export const init_game: (a: number, b: number) => [number, number];
export const init_menu: () => [number, number];
export const init_progress: () => [number, number];
export const main: () => void;
export const nav_to: (a: number, b: number) => [number, number];
export const prepare_game: (a: number, b: number, c: number, d: number) => [number, number];
export const reset_all_progress: () => [number, number];
export const restart_game: () => [number, number];
export const select_cube: (a: number) => [number, number];
export const show_game_over: (a: number, b: number) => [number, number];
export const show_menu: () => [number, number];
export const set_selected_cube: (a: number) => [number, number];
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
